CREATE OR REPLACE TASK LANDING.LOAD_YOUTUBE_API_DATA_TASK
WAREHOUSE = YT_SF_LOAD_WH
SCHEDULE = 'USING CRON 0 0 * * * Europe/Budapest' -- Runs every midnight Budapest time
AS
CALL LANDING.EXTRACT_YOUTUBE_METRICS_SP();