-- 1. Create Task to Load Raw Data
-- Resides in RAW schema, orchestrates the incremental load from the landing stream.

CREATE OR REPLACE TASK RAW.LOAD_YOUTUBE_RAW_DATA_TASK
WAREHOUSE = YT_SF_TRANSFORM_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
WHEN SYSTEM$STREAM_HAS_DATA('LANDING.YOUTUBE_RAW_DATA_STREAM')
AS
INSERT INTO RAW.YOUTUBE_RAW_DATA (RAW_JSON, EXTRACTED_AT)
SELECT RAW_JSON, EXTRACTED_AT 
FROM LANDING.YOUTUBE_RAW_DATA_STREAM 
WHERE METADATA$ACTION = 'INSERT';
