USE ROLE ACCOUNTADMIN;

-- 0. Create Resource Monitors to cap spending
-- Note: 5 Euros is roughly equivalent to 2 Snowflake Credits (depending on your tier)
CREATE RESOURCE MONITOR IF NOT EXISTS YT_SF_CICD_RM
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS 
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS YT_SF_TRANSFORM_RM
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS 
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS YT_SF_ADMIN_RM
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS 
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

-- 1. Create Warehouses under ACCOUNTADMIN so we can natively assign the monitors
CREATE WAREHOUSE IF NOT EXISTS YT_SF_CICD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  RESOURCE_MONITOR = YT_SF_CICD_RM
  COMMENT = 'Warehouse for CI/CD ingestion and deployment';

CREATE WAREHOUSE IF NOT EXISTS YT_SF_TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  RESOURCE_MONITOR = YT_SF_TRANSFORM_RM
  COMMENT = 'Warehouse for transformation, dbt, and manual queries';

CREATE WAREHOUSE IF NOT EXISTS YT_SF_ADMIN_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  RESOURCE_MONITOR = YT_SF_ADMIN_RM
  COMMENT = 'Warehouse for admin related tasks and debugging';

-- Transfer ownership immediately back to Sysadmin (it will later be moved to Admin role in grants step)
GRANT OWNERSHIP ON WAREHOUSE YT_SF_CICD_WH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_ADMIN_WH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;

USE ROLE SYSADMIN;

-- ==============================================================
-- 2. CREATE DATABASES (PROD and DEV)
-- ==============================================================
CREATE DATABASE IF NOT EXISTS YT_SF_PROD
  COMMENT = 'Production database for YouTube Metrics pipeline';

CREATE DATABASE IF NOT EXISTS YT_SF_DEV
  COMMENT = 'Development database for feature testing and CI/CD validation';

-- ==============================================================
-- 3. CREATE MANAGED ACCESS SCHEMAS
-- ==============================================================
-- PROD SCHEMAS
CREATE SCHEMA IF NOT EXISTS YT_SF_PROD.LANDING WITH MANAGED ACCESS
  COMMENT = 'Transient landing area for raw data extracts';
CREATE SCHEMA IF NOT EXISTS YT_SF_PROD.RAW WITH MANAGED ACCESS
  COMMENT = 'Persistent historical storage layer';
CREATE SCHEMA IF NOT EXISTS YT_SF_PROD.STAGING WITH MANAGED ACCESS
  COMMENT = 'Staging layer for transformed metrics';
CREATE SCHEMA IF NOT EXISTS YT_SF_PROD.MART WITH MANAGED ACCESS
  COMMENT = 'Presentation layer for visualizations';
CREATE SCHEMA IF NOT EXISTS YT_SF_PROD.TECH WITH MANAGED ACCESS
  COMMENT = 'Technical schema for CI/CD tracking and logs';

-- DEV SCHEMAS
CREATE SCHEMA IF NOT EXISTS YT_SF_DEV.LANDING WITH MANAGED ACCESS
  COMMENT = 'Transient landing area for raw data extracts (DEV)';
CREATE SCHEMA IF NOT EXISTS YT_SF_DEV.RAW WITH MANAGED ACCESS
  COMMENT = 'Persistent historical storage layer (DEV)';
CREATE SCHEMA IF NOT EXISTS YT_SF_DEV.STAGING WITH MANAGED ACCESS
  COMMENT = 'Staging layer for transformed metrics (DEV)';
CREATE SCHEMA IF NOT EXISTS YT_SF_DEV.MART WITH MANAGED ACCESS
  COMMENT = 'Presentation layer for visualizations (DEV)';
CREATE SCHEMA IF NOT EXISTS YT_SF_DEV.TECH WITH MANAGED ACCESS
  COMMENT = 'Technical schema for CI/CD tracking and logs (DEV)';
