USE ROLE SECURITYADMIN;

-- ==============================================================
-- 1. OBJECT ROLES: PROD SCHEMAS
-- ==============================================================
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_LANDING_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_LANDING_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_LANDING_SFULL;
GRANT ROLE _YT_SF_PROD_LANDING_SR TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT ROLE _YT_SF_PROD_LANDING_SW TO ROLE _YT_SF_PROD_LANDING_SFULL;

CREATE ROLE IF NOT EXISTS _YT_SF_PROD_RAW_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_RAW_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_RAW_SFULL;
GRANT ROLE _YT_SF_PROD_RAW_SR TO ROLE _YT_SF_PROD_RAW_SW;
GRANT ROLE _YT_SF_PROD_RAW_SW TO ROLE _YT_SF_PROD_RAW_SFULL;

CREATE ROLE IF NOT EXISTS _YT_SF_PROD_STAGING_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_STAGING_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_STAGING_SFULL;
GRANT ROLE _YT_SF_PROD_STAGING_SR TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT ROLE _YT_SF_PROD_STAGING_SW TO ROLE _YT_SF_PROD_STAGING_SFULL;

CREATE ROLE IF NOT EXISTS _YT_SF_PROD_MART_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_MART_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_PROD_MART_SFULL;
GRANT ROLE _YT_SF_PROD_MART_SR TO ROLE _YT_SF_PROD_MART_SW;
GRANT ROLE _YT_SF_PROD_MART_SW TO ROLE _YT_SF_PROD_MART_SFULL;

-- ==============================================================
-- 2. OBJECT ROLES: DEV SCHEMAS
-- ==============================================================
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_LANDING_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_LANDING_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_LANDING_SFULL;
GRANT ROLE _YT_SF_DEV_LANDING_SR TO ROLE _YT_SF_DEV_LANDING_SW;
GRANT ROLE _YT_SF_DEV_LANDING_SW TO ROLE _YT_SF_DEV_LANDING_SFULL;

CREATE ROLE IF NOT EXISTS _YT_SF_DEV_RAW_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_RAW_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_RAW_SFULL;
GRANT ROLE _YT_SF_DEV_RAW_SR TO ROLE _YT_SF_DEV_RAW_SW;
GRANT ROLE _YT_SF_DEV_RAW_SW TO ROLE _YT_SF_DEV_RAW_SFULL;

CREATE ROLE IF NOT EXISTS _YT_SF_DEV_STAGING_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_STAGING_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_STAGING_SFULL;
GRANT ROLE _YT_SF_DEV_STAGING_SR TO ROLE _YT_SF_DEV_STAGING_SW;
GRANT ROLE _YT_SF_DEV_STAGING_SW TO ROLE _YT_SF_DEV_STAGING_SFULL;

CREATE ROLE IF NOT EXISTS _YT_SF_DEV_MART_SR;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_MART_SW;
CREATE ROLE IF NOT EXISTS _YT_SF_DEV_MART_SFULL;
GRANT ROLE _YT_SF_DEV_MART_SR TO ROLE _YT_SF_DEV_MART_SW;
GRANT ROLE _YT_SF_DEV_MART_SW TO ROLE _YT_SF_DEV_MART_SFULL;

-- ==============================================================
-- 3. FUNCTIONAL ROLES
-- ==============================================================
-- PROD Roles
CREATE ROLE IF NOT EXISTS YT_SF_PROD_ADMIN_ROLE COMMENT = 'Admin for PROD DB';
CREATE ROLE IF NOT EXISTS YT_SF_PROD_CICD_ROLE COMMENT = 'Deployer for PROD DB';
CREATE ROLE IF NOT EXISTS YT_SF_PROD_TRANSFORM_ROLE COMMENT = 'DBT execution in PROD DB';
CREATE ROLE IF NOT EXISTS YT_SF_PROD_LOAD_ROLE COMMENT = 'Python extraction into PROD Landing';

-- DEV Roles
CREATE ROLE IF NOT EXISTS YT_SF_DEV_ADMIN_ROLE COMMENT = 'Admin for DEV DB';
CREATE ROLE IF NOT EXISTS YT_SF_DEV_CICD_ROLE COMMENT = 'Deployer for DEV DB';
CREATE ROLE IF NOT EXISTS YT_SF_DEV_TRANSFORM_ROLE COMMENT = 'DBT execution in DEV DB';
CREATE ROLE IF NOT EXISTS YT_SF_DEV_LOAD_ROLE COMMENT = 'Python extraction into DEV Landing';

-- Ensure underlying roles roll up into the Admin roles
GRANT ROLE YT_SF_PROD_CICD_ROLE TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE YT_SF_PROD_TRANSFORM_ROLE TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE YT_SF_PROD_LOAD_ROLE TO ROLE YT_SF_PROD_ADMIN_ROLE;

GRANT ROLE YT_SF_DEV_CICD_ROLE TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE YT_SF_DEV_TRANSFORM_ROLE TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE YT_SF_DEV_LOAD_ROLE TO ROLE YT_SF_DEV_ADMIN_ROLE;

-- Finally, roll up the Admin roles to SYSADMIN
GRANT ROLE YT_SF_PROD_ADMIN_ROLE TO ROLE SYSADMIN;
GRANT ROLE YT_SF_DEV_ADMIN_ROLE TO ROLE SYSADMIN;
