USE ROLE SECURITYADMIN;

-- ==============================================================
-- 1. ASSIGN OBJECT ROLES TO PROD FUNCTIONAL ROLES
-- ==============================================================
-- PROD ADMIN
GRANT ROLE _YT_SF_PROD_LANDING_SFULL TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_RAW_SFULL TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_STAGING_SFULL TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_MART_SFULL TO ROLE YT_SF_PROD_ADMIN_ROLE;

-- PROD CICD
GRANT ROLE _YT_SF_PROD_LANDING_SFULL TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_RAW_SFULL TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_STAGING_SFULL TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_MART_SFULL TO ROLE YT_SF_PROD_CICD_ROLE;

-- PROD LOAD
GRANT ROLE _YT_SF_PROD_LANDING_SFULL TO ROLE YT_SF_PROD_LOAD_ROLE;

-- PROD TRANSFORM
GRANT ROLE _YT_SF_PROD_RAW_SFULL TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT ROLE _YT_SF_PROD_STAGING_SFULL TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT ROLE _YT_SF_PROD_MART_SFULL TO ROLE YT_SF_PROD_TRANSFORM_ROLE;


-- TECH
GRANT ROLE _YT_SF_PROD_TECH_SFULL TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_TECH_SFULL TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_TECH_SR TO ROLE YT_SF_PROD_LOAD_ROLE;
GRANT ROLE _YT_SF_PROD_TECH_SW TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

-- TECH_BKP
GRANT ROLE _YT_SF_PROD_TECH_BKP_SFULL TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_TECH_BKP_SFULL TO ROLE YT_SF_PROD_CICD_ROLE;

-- ==============================================================
-- 2. ASSIGN OBJECT ROLES TO DEV FUNCTIONAL ROLES
-- ==============================================================
-- DEV ADMIN
GRANT ROLE _YT_SF_DEV_LANDING_SFULL TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE _YT_SF_DEV_RAW_SFULL TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE _YT_SF_DEV_STAGING_SFULL TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE _YT_SF_DEV_MART_SFULL TO ROLE YT_SF_DEV_ADMIN_ROLE;

-- DEV CICD
GRANT ROLE _YT_SF_DEV_LANDING_SFULL TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT ROLE _YT_SF_DEV_RAW_SFULL TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT ROLE _YT_SF_DEV_STAGING_SFULL TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT ROLE _YT_SF_DEV_MART_SFULL TO ROLE YT_SF_DEV_CICD_ROLE;

-- DEV LOAD
GRANT ROLE _YT_SF_DEV_LANDING_SFULL TO ROLE YT_SF_DEV_LOAD_ROLE;

-- DEV TRANSFORM
GRANT ROLE _YT_SF_DEV_RAW_SFULL TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT ROLE _YT_SF_DEV_STAGING_SFULL TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT ROLE _YT_SF_DEV_MART_SFULL TO ROLE YT_SF_DEV_TRANSFORM_ROLE;



-- TECH
GRANT ROLE _YT_SF_DEV_TECH_SFULL TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE _YT_SF_DEV_TECH_SFULL TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT ROLE _YT_SF_DEV_TECH_SR TO ROLE YT_SF_DEV_LOAD_ROLE;
GRANT ROLE _YT_SF_DEV_TECH_SW TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

-- TECH_BKP
GRANT ROLE _YT_SF_DEV_TECH_BKP_SFULL TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT ROLE _YT_SF_DEV_TECH_BKP_SFULL TO ROLE YT_SF_DEV_CICD_ROLE;

-- ==============================================================
-- 3. HIGH LEVEL INFRASTRUCTURE GRANTS
-- ==============================================================
-- Account Level Security & Task Privileges
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

-- Grant Warehouse Usage uniformly to both DEV and PROD
GRANT USAGE ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_PROD_CICD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_LOAD_WH TO ROLE YT_SF_PROD_LOAD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

GRANT USAGE ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_DEV_CICD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_LOAD_WH TO ROLE YT_SF_DEV_LOAD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

GRANT USAGE ON WAREHOUSE YT_SF_ADMIN_WH TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_ADMIN_WH TO ROLE YT_SF_DEV_ADMIN_ROLE;

-- Database & Warehouse Ownership
GRANT OWNERSHIP ON DATABASE YT_SF_PROD TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.TECH TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.TECH_BKP TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE YT_SF_DEV TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_DEV.LANDING TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_DEV.RAW TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_DEV.STAGING TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_DEV.MART TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_DEV.TECH TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_DEV.TECH_BKP TO ROLE YT_SF_DEV_ADMIN_ROLE REVOKE CURRENT GRANTS;

-- Only PROD Admin owns core warehouses to prevent duplication faults, DEV Admin gets OPERATE
GRANT OWNERSHIP ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_ADMIN_WH TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_LOAD_WH TO ROLE YT_SF_PROD_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OPERATE ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT OPERATE ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT OPERATE ON WAREHOUSE YT_SF_ADMIN_WH TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT OPERATE ON WAREHOUSE YT_SF_LOAD_WH TO ROLE YT_SF_DEV_ADMIN_ROLE;


-- ==============================================================
-- 4. PROD SCHEMA PERMISSIONS
-- ==============================================================
USE ROLE SYSADMIN;

-- PROD.LANDING
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;

-- PROD.RAW
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;

-- PROD.STAGING
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;

-- PROD.MART
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT CREATE STREAMLIT ON SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;



-- PROD.TECH
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_TECH_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE, CREATE SECRET, CREATE NETWORK RULE, CREATE GIT REPOSITORY ON SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE SECRETS IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE NETWORK RULES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE GIT REPOSITORIES IN SCHEMA YT_SF_PROD.TECH TO ROLE _YT_SF_PROD_TECH_SFULL;

-- PROD.TECH_BKP
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE _YT_SF_PROD_TECH_BKP_SFULL;

-- ==============================================================
-- 5. DEV SCHEMA PERMISSIONS
-- ==============================================================

-- DEV.LANDING
GRANT USAGE ON DATABASE YT_SF_DEV TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT USAGE ON SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.LANDING TO ROLE _YT_SF_DEV_LANDING_SFULL;

-- DEV.RAW
GRANT USAGE ON DATABASE YT_SF_DEV TO ROLE _YT_SF_DEV_RAW_SR;
GRANT USAGE ON SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.RAW TO ROLE _YT_SF_DEV_RAW_SFULL;

-- DEV.STAGING
GRANT USAGE ON DATABASE YT_SF_DEV TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT USAGE ON SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.STAGING TO ROLE _YT_SF_DEV_STAGING_SFULL;

-- DEV.MART
GRANT USAGE ON DATABASE YT_SF_DEV TO ROLE _YT_SF_DEV_MART_SR;
GRANT USAGE ON SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT CREATE STREAMLIT ON SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.MART TO ROLE _YT_SF_DEV_MART_SFULL;


-- DEV.TECH
GRANT USAGE ON DATABASE YT_SF_DEV TO ROLE _YT_SF_DEV_TECH_SR;
GRANT USAGE ON SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE, CREATE SECRET, CREATE NETWORK RULE, CREATE GIT REPOSITORY ON SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE SECRETS IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE NETWORK RULES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;
GRANT OWNERSHIP ON FUTURE GIT REPOSITORIES IN SCHEMA YT_SF_DEV.TECH TO ROLE _YT_SF_DEV_TECH_SFULL;

-- DEV.TECH_BKP
GRANT USAGE ON DATABASE YT_SF_DEV TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT USAGE ON SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SR;

GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SW;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE _YT_SF_DEV_TECH_BKP_SFULL;

-- ==============================================================
-- 6. COMPUTE OBJECT OWNERSHIP ROUTING (FUNCTIONAL ROLES)
-- ==============================================================
-- Because Schema Object Roles (_SFULL) do not have warehouse USAGE, they cannot execute compute objects.
-- Therefore, future ownership of Tasks, Dynamic Tables, and Streamlits is mapped directly to the Functional Roles.

-- PROD Compute Ownership
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_PROD_LOAD_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_PROD_LOAD_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE STREAMLIT IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.TECH TO ROLE YT_SF_PROD_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH TO ROLE YT_SF_PROD_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE YT_SF_PROD_ADMIN_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.TECH_BKP TO ROLE YT_SF_PROD_ADMIN_ROLE;

-- DEV Compute Ownership
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_DEV.LANDING TO ROLE YT_SF_DEV_LOAD_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.LANDING TO ROLE YT_SF_DEV_LOAD_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_DEV.RAW TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.RAW TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_DEV.STAGING TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.STAGING TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_DEV.MART TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.MART TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE STREAMLIT IN SCHEMA YT_SF_DEV.MART TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_DEV.TECH TO ROLE YT_SF_DEV_TRANSFORM_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH TO ROLE YT_SF_DEV_TRANSFORM_ROLE;

GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE YT_SF_DEV_ADMIN_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_DEV.TECH_BKP TO ROLE YT_SF_DEV_ADMIN_ROLE;
