USE ROLE SECURITYADMIN;

-- ==============================================================
-- 1. ASSIGN OBJECT ROLES TO FUNCTIONAL ROLES
-- ==============================================================
-- ADMIN: Has Full privileges to govern the entire database
GRANT ROLE _YT_SF_PROD_LANDING_SFULL TO ROLE YT_SF_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_RAW_SFULL TO ROLE YT_SF_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_STAGING_SFULL TO ROLE YT_SF_ADMIN_ROLE;
GRANT ROLE _YT_SF_PROD_MART_SFULL TO ROLE YT_SF_ADMIN_ROLE;

-- CICD: Deployer Role (needs to deploy assets like tables, views, streams across all schemas)
GRANT ROLE _YT_SF_PROD_LANDING_SFULL TO ROLE YT_SF_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_RAW_SFULL TO ROLE YT_SF_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_STAGING_SFULL TO ROLE YT_SF_CICD_ROLE;
GRANT ROLE _YT_SF_PROD_MART_SFULL TO ROLE YT_SF_CICD_ROLE;

-- LOAD: Specifically mapped to ingest python pipelines
-- SFULL for Landing because pipeline creates and drops the transient landing table
GRANT ROLE _YT_SF_PROD_LANDING_SFULL TO ROLE YT_SF_LOAD_ROLE;

-- TRANSFORM: dbt transformations
-- Manages merging Landing objects into persistent RAW history, and generates STAGING/MART models.
GRANT ROLE _YT_SF_PROD_RAW_SFULL TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ROLE _YT_SF_PROD_STAGING_SFULL TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ROLE _YT_SF_PROD_MART_SFULL TO ROLE YT_SF_TRANSFORM_ROLE;

-- ==============================================================
-- 2. HIGH LEVEL INFRASTRUCTURE GRANTS (Functional Direct Grants)
-- ==============================================================
GRANT USAGE ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_CICD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_LOAD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_TRANSFORM_ROLE;

GRANT OWNERSHIP ON DATABASE YT_SF_PROD TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;

-- ==============================================================
-- 3. PERMISSIONS FOR SCHEMA: LANDING
-- ==============================================================
USE ROLE SYSADMIN;
/* SR Permissions */
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SR;

/* SW Permissions */
GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SW;

/* SFULL Permissions */
GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT ON SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.LANDING TO ROLE _YT_SF_PROD_LANDING_SFULL;

-- ==============================================================
-- 4. PERMISSIONS FOR SCHEMA: RAW
-- ==============================================================
/* SR Permissions */
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SR;

/* SW Permissions */
GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SW;

/* SFULL Permissions */
GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT ON SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.RAW TO ROLE _YT_SF_PROD_RAW_SFULL;

-- ==============================================================
-- 5. PERMISSIONS FOR SCHEMA: STAGING
-- ==============================================================
/* SR Permissions */
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SR;

/* SW Permissions */
GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SW;

/* SFULL Permissions */
GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT ON SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.STAGING TO ROLE _YT_SF_PROD_STAGING_SFULL;

-- ==============================================================
-- 6. PERMISSIONS FOR SCHEMA: MART
-- ==============================================================
/* SR Permissions */
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SR;

/* SW Permissions */
GRANT INSERT, UPDATE, TRUNCATE, REFERENCES, DELETE ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SW;

/* SFULL Permissions */
GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT ON SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT SELECT, MONITOR, OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT CREATE STREAMLIT ON SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA YT_SF_PROD.MART TO ROLE _YT_SF_PROD_MART_SFULL;
