USE ROLE SECURITYADMIN;

-- ==============================================================
-- 1. OWNERSHIP GRANTS (ADMIN ROLE)
-- ==============================================================
-- Transfer object ownership to the Admin Role
GRANT OWNERSHIP ON DATABASE YT_SF_PROD TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_ADMIN_ROLE REVOKE CURRENT GRANTS;

-- Admin Needs broad privileges inside these schemas
GRANT ALL PRIVILEGES ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_ADMIN_ROLE;

-- ==============================================================
-- 2. INFRASTRUCTURE ACCESS GRANTS
-- ==============================================================
GRANT USAGE ON WAREHOUSE YT_SF_CICD_WH TO ROLE YT_SF_CICD_ROLE;
GRANT USAGE ON WAREHOUSE YT_SF_TRANSFORM_WH TO ROLE YT_SF_TRANSFORM_ROLE;

GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE YT_SF_CICD_ROLE;
GRANT USAGE ON DATABASE YT_SF_PROD TO ROLE YT_SF_TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;
GRANT USAGE ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;
GRANT USAGE ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT USAGE ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;

GRANT USAGE ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;

-- ==============================================================
-- 3. CICD ROLE DEPLOYMENT CAPABILITIES
-- ==============================================================
-- CICD deploys assets into all schemas (landing, raw, staging, mart)
GRANT CREATE TABLE ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE VIEW ON SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.LANDING TO ROLE YT_SF_CICD_ROLE;

GRANT CREATE TABLE ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE VIEW ON SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_CICD_ROLE;

GRANT CREATE TABLE ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE VIEW ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_CICD_ROLE;

GRANT CREATE TABLE ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE VIEW ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_CICD_ROLE;

-- ==============================================================
-- 4. TRANSFORM ROLE DUTIES (dbt and Manual usage)
-- ==============================================================
-- Transform needs read access on RAW, and read/write/deploy access to STAGING and MART
GRANT SELECT ON ALL TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.RAW TO ROLE YT_SF_TRANSFORM_ROLE;

-- Staging Create/Modify
GRANT CREATE TABLE ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT CREATE VIEW ON SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.STAGING TO ROLE YT_SF_TRANSFORM_ROLE;

-- Mart Create/Modify
GRANT CREATE TABLE ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT CREATE VIEW ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA YT_SF_PROD.MART TO ROLE YT_SF_TRANSFORM_ROLE;
