-- 3. External Access Integration: Bind the network rule and secret together
-- Account-level object. Binds the TECH.YOUTUBE_API_NETWORK_RULE and TECH.YOUTUBE_API_KEY_SECRET.

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_YOUTUBE_API_INTEGRATION
  ALLOWED_NETWORK_RULES = (TECH.YOUTUBE_API_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (TECH.YOUTUBE_API_KEY_SECRET)
  ENABLED = TRUE
  COMMENT = '{{SNOWFLAKE_ENVIRONMENT}} integration granting Snowpark access to YouTube API';

-- 4. Grant USAGE on the integration and secret to the LOAD role
-- (Future procedures owned by LOAD_ROLE need these to authenticate)
GRANT USAGE ON INTEGRATION YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_YOUTUBE_API_INTEGRATION TO ROLE YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_LOAD_ROLE;
GRANT READ ON SECRET TECH.YOUTUBE_API_KEY_SECRET TO ROLE YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_LOAD_ROLE;

-- Also grant to CICD so it can deploy procedures that reference the integration
GRANT USAGE ON INTEGRATION YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_YOUTUBE_API_INTEGRATION TO ROLE YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_CICD_ROLE;
GRANT READ ON SECRET TECH.YOUTUBE_API_KEY_SECRET TO ROLE YT_SF_{{SNOWFLAKE_ENVIRONMENT}}_CICD_ROLE;
