CREATE OR REPLACE STREAMLIT MART.YOUTUBE_METRICS_DASHBOARD
  ROOT_LOCATION = '@{{SNOWFLAKE_DATABASE}}.MART.STREAMLIT_STAGE'
  MAIN_FILE = 'Home.py'
  QUERY_WAREHOUSE = 'YT_SF_REPORTING_WH'
  COMMENT = 'YouTube metrics daily views dashboard';
